class CurrencyUtil {
  static String getCountryName(String fiatCode) {
    return _currencyMap[fiatCode] ?? '';
  }

  static const _currencyMap = {
    'ADP': 'Andorra',
    'AED': 'United Arab Emirates',
    'AFA': 'Afghanistan',
    'AFN': 'Afghanistan',
    'ALK': 'Albania',
    'ALL': 'Albania',
    'AMD': 'Armenia',
    'ANG': 'Netherlands Antilles',
    'AOA': 'Angola',
    'AOK': 'Angola',
    'AON': 'Angola',
    'AOR': 'Angola',
    'ARA': 'Argentina',
    'ARP': 'Argentina',
    'ARS': 'Argentina',
    'ARY': 'Argentina',
    'ATS': 'Austria',
    'AUD': 'Tuvalu',
    'AWG': 'Aruba',
    'AYM': 'Azerbaijan',
    'AZM': 'Azerbaijan',
    'AZN': 'Azerbaijan',
    'BAD': 'Bosnia And Herzegovina',
    'BAM': 'Bosnia And Herzegovina',
    'BBD': 'Barbados',
    'BDT': 'Bangladesh',
    'BEC': 'Belgium',
    'BEF': 'Belgium',
    'BEL': 'Belgium',
    'BGJ': 'Bulgaria',
    'BGK': 'Bulgaria',
    'BGL': 'Bulgaria',
    'BGN': 'Bulgaria',
    'BHD': 'Bahrain',
    'BIF': 'Burundi',
    'BMD': 'Bermuda',
    'BND': 'Brunei Darussalam',
    'BOB': 'Bolivia',
    'BOP': 'Bolivia',
    'BOV': 'Bolivia',
    'BRB': 'Brazil',
    'BRC': 'Brazil',
    'BRE': 'Brazil',
    'BRL': 'Brazil',
    'BRN': 'Brazil',
    'BRR': 'Brazil',
    'BSD': 'Bahamas',
    'BTN': 'Bhutan',
    'BUK': 'Burma',
    'BWP': 'Botswana',
    'BYB': 'Belarus',
    'BYN': 'Belarus',
    'BYR': 'Belarus',
    'BZD': 'Belize',
    'CAD': 'Canada',
    'CDF': 'Congo',
    'CHC': 'Switzerland',
    'CHE': 'Switzerland',
    'CHF': 'Switzerland',
    'CHW': 'Switzerland',
    'CLF': 'Chile',
    'CLP': 'Chile',
    'CNY': 'China',
    'COP': 'Colombia',
    'COU': 'Colombia',
    'CRC': 'Costa Rica',
    'CSD': 'Serbia And Montenegro',
    'CSJ': 'Czechoslovakia',
    'CSK': 'Czechoslovakia',
    'CUC': 'Cuba',
    'CUP': 'Cuba',
    'CVE': 'Cabo Verde',
    'CYP': 'Cyprus',
    'CZK': 'Czechia',
    'DDM': 'German Democratic Republic',
    'DEM': 'Germany',
    'DJF': 'Djibouti',
    'DKK': 'Greenland',
    'DOP': 'Dominican Republic',
    'DZD': 'Algeria',
    'ECS': 'Ecuador',
    'ECV': 'Ecuador',
    'EEK': 'Estonia',
    'EGP': 'Egypt',
    'ERN': 'Eritrea',
    'ESA': 'Spain',
    'ESB': 'Spain',
    'ESP': 'Spain',
    'ETB': 'Ethiopia',
    'EUR': 'Serbia And Montenegro',
    'FIM': 'Finland',
    'FJD': 'Fiji',
    'FKP': 'Falkland Islands [Malvinas]',
    'FRF': 'Saint-Barthélemy',
    'GBP': 'United Kingdom Of Great Britain And Northern Ireland',
    'GEK': 'Georgia',
    'GEL': 'Georgia',
    'GHC': 'Ghana',
    'GHP': 'Ghana',
    'GHS': 'Ghana',
    'GIP': 'Gibraltar',
    'GMD': 'Gambia',
    'GNE': 'Guinea',
    'GNF': 'Guinea',
    'GNS': 'Guinea',
    'GQE': 'Equatorial Guinea',
    'GRD': 'Greece',
    'GTQ': 'Guatemala',
    'GWE': 'Guinea-Bissau',
    'GWP': 'Guinea-Bissau',
    'GYD': 'Guyana',
    'HKD': 'Hong Kong',
    'HNL': 'Honduras',
    'HRD': 'Croatia',
    'HRK': 'Croatia',
    'HTG': 'Haiti',
    'HUF': 'Hungary',
    'IDR': 'Timor-Leste',
    'IEP': 'Ireland',
    'ILP': 'Israel',
    'ILR': 'Israel',
    'ILS': 'Israel',
    'INR': 'India',
    'IQD': 'Iraq',
    'IRR': 'Iran',
    'ISJ': 'Iceland',
    'ISK': 'Iceland',
    'ITL': 'San Marino',
    'JMD': 'Jamaica',
    'JOD': 'Jordan',
    'JPY': 'Japan',
    'KES': 'Kenya',
    'KGS': 'Kyrgyzstan',
    'KHR': 'Cambodia',
    'KMF': 'Comoros',
    'KPW': 'Korea',
    'KRW': 'Korea',
    'KWD': 'Kuwait',
    'KYD': 'Cayman Islands',
    'KZT': 'Kazakhstan',
    'LAJ': 'Lao',
    'LAK': "Lao People's Democratic Republic",
    'LBP': 'Lebanon',
    'LKR': 'Sri Lanka',
    'LRD': 'Liberia',
    'LSL': 'Lesotho',
    'LSM': 'Lesotho',
    'LTL': 'Lithuania',
    'LTT': 'Lithuania',
    'LUC': 'Luxembourg',
    'LUF': 'Luxembourg',
    'LUL': 'Luxembourg',
    'LVL': 'Latvia',
    'LVR': 'Latvia',
    'LYD': 'Libya',
    'MAD': 'Western Sahara',
    'MDL': 'Moldova',
    'MGA': 'Madagascar',
    'MGF': 'Madagascar',
    'MKD': 'North Macedonia',
    'MLF': 'Mali',
    'MMK': 'Myanmar',
    'MNT': 'Mongolia',
    'MOP': 'Macao',
    'MRO': 'Mauritania',
    'MRU': 'Mauritania',
    'MTL': 'Malta',
    'MTP': 'Malta',
    'MUR': 'Mauritius',
    'MVQ': 'Maldives',
    'MVR': 'Maldives',
    'MWK': 'Malawi',
    'MXN': 'Mexico',
    'MXP': 'Mexico',
    'MXV': 'Mexico',
    'MYR': 'Malaysia',
    'MZE': 'Mozambique',
    'MZM': 'Mozambique',
    'MZN': 'Mozambique',
    'NAD': 'Namibia',
    'NGN': 'Nigeria',
    'NIC': 'Nicaragua',
    'NIO': 'Nicaragua',
    'NLG': 'Netherlands',
    'NOK': 'Svalbard And Jan Mayen',
    'NPR': 'Nepal',
    'NZD': 'Tokelau',
    'OMR': 'Oman',
    'PAB': 'Panama',
    'PEH': 'Peru',
    'PEI': 'Peru',
    'PEN': 'Peru',
    'PES': 'Peru',
    'PGK': 'Papua New Guinea',
    'PHP': 'Philippines',
    'PKR': 'Pakistan',
    'PLN': 'Poland',
    'PLZ': 'Poland',
    'PTE': 'Portugal',
    'PYG': 'Paraguay',
    'QAR': 'Qatar',
    'RHD': 'Southern Rhodesia',
    'ROK': 'Romania',
    'ROL': 'Romania',
    'RON': 'Romania',
    'RSD': 'Serbia',
    'RUB': 'Russian Federation',
    'RUR': 'Uzbekistan',
    'RWF': 'Rwanda',
    'SAR': 'Saudi Arabia',
    'SBD': 'Solomon Islands',
    'SCR': 'Seychelles',
    'SDD': 'Sudan',
    'SDG': 'South Sudan',
    'SDP': 'Sudan',
    'SEK': 'Sweden',
    'SGD': 'Singapore',
    'SHP': 'Saint Helena, Ascension And Tristan Da Cunha',
    'SIT': 'Slovenia',
    'SKK': 'Slovakia',
    'SLL': 'Sierra Leone',
    'SOS': 'Somalia',
    'SRD': 'Suriname',
    'SRG': 'Suriname',
    'SSP': 'South Sudan',
    'STD': 'Sao Tome And Principe',
    'STN': 'Sao Tome And Principe',
    'SUR': 'Union Of Soviet Socialist Republics',
    'SVC': 'El Salvador',
    'SYP': 'Syrian Arab Republic',
    'SZL': 'Swaziland',
    'THB': 'Thailand',
    'TJR': 'Tajikistan',
    'TJS': 'Tajikistan',
    'TMM': 'Turkmenistan',
    'TMT': 'Turkmenistan',
    'TND': 'Tunisia',
    'TOP': 'Tonga',
    'TPE': 'Timor-Leste',
    'TRL': 'Turkey',
    'TRY': 'Turkey',
    'TTD': 'Trinidad And Tobago',
    'TWD': 'Taiwan',
    'TZS': 'Tanzania, United Republic Of',
    'UAH': 'Ukraine',
    'UAK': 'Ukraine',
    'UGS': 'Uganda',
    'UGW': 'Uganda',
    'UGX': 'Uganda',
    'USD': 'United States Of America',
    'USS': 'United States',
    'UYI': 'Uruguay',
    'UYN': 'Uruguay',
    'UYP': 'Uruguay',
    'UYU': 'Uruguay',
    'UYW': 'Uruguay',
    'UZS': 'Uzbekistan',
    'VEB': 'Venezuela',
    'VEF': 'Venezuela',
    'VES': 'Venezuela',
    'VNC': 'Vietnam',
    'VND': 'Viet Nam',
    'VUV': 'Vanuatu',
    'WST': 'Samoa',
    'XAF': 'Gabon',
    'XAG': 'Zz11_silver',
    'XAU': 'Zz08_gold',
    'XBA': 'Zz01_bond Markets Unit European_eurco',
    'XBB': 'Zz02_bond Markets Unit European_emu-6',
    'XBC': 'Zz03_bond Markets Unit European_eua-9',
    'XBD': 'Zz04_bond Markets Unit European_eua-17',
    'XCD': 'Saint Vincent And The Grenadines',
    'XDR': 'International Monetary Fund',
    'XEU': 'European Monetary Co-Operation Fund',
    'XFO': 'Zz01_gold-Franc',
    'XFU': 'Zz05_uic-Franc',
    'XOF': 'Togo',
    'XPD': 'Zz09_palladium',
    'XPF': 'Wallis And Futuna',
    'XPT': 'Zz10_platinum',
    'XRE': 'Zz02_rinet Funds Code',
    'XSU': 'Sistema Unitario De Compensacion Regional De Pagos "Sucre',
    'XTS': 'Zz06_testing_code',
    'XUA': 'Member Countries Of The African Development Bank Group',
    'XXX': 'Zz07_no_currency',
    'YDD': 'Yemen, Democratic',
    'YER': 'Yemen',
    'YUD': 'Yugoslavia',
    'YUM': 'Yugoslavia',
    'YUN': 'Yugoslavia',
    'ZAL': 'South Africa',
    'ZAR': 'South Africa',
    'ZMK': 'Zambia',
    'ZMW': 'Zambia',
    'ZRN': 'Zaire',
    'ZRZ': 'Zaire',
    'ZWC': 'Zimbabwe',
    'ZWD': 'Zimbabwe',
    'ZWL': 'Zimbabwe',
    'ZWN': 'Zimbabwe',
    'ZWR': 'Zimbabwe'
  };
}
