// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm2r_FDyoKcBa8rPs_uf9sfbjKNwqbfv0',
    appId: '1:172098015365:web:dd82dcf246f411152b99ec',
    messagingSenderId: '172098015365',
    projectId: 'leaf-loans-dev',
    authDomain: 'leaf-loans-dev.firebaseapp.com',
    storageBucket: 'leaf-loans-dev.appspot.com',
    measurementId: 'G-PVGVBG20VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvgwaafcKYkTLxcaM6rwJolL0Vx41ekPA',
    appId: '1:172098015365:android:109df57c1e6d5a092b99ec',
    messagingSenderId: '172098015365',
    projectId: 'leaf-loans-dev',
    storageBucket: 'leaf-loans-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9DrpESksVPtA8o_okGOKjvAsU99ye2QI',
    appId: '1:172098015365:ios:e57f2600cb7cef802b99ec',
    messagingSenderId: '172098015365',
    projectId: 'leaf-loans-dev',
    storageBucket: 'leaf-loans-dev.appspot.com',
    androidClientId: '172098015365-sop44n0o30mp32alajon9jv9psbafvgl.apps.googleusercontent.com',
    iosClientId: '172098015365-mj3sl5eu6sjo4e6dh9jj6i7p384rlom8.apps.googleusercontent.com',
    iosBundleId: 'com.leafglobalfintech.loanapp',
  );
}
